// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCiY-CfhN388KIk54Q4W2BqDkNBdBTcM',
    appId: '1:549297268901:web:ce3b4e91bff2dbf700454c',
    messagingSenderId: '549297268901',
    projectId: 'abschlussarbeit-firstapp',
    authDomain: 'abschlussarbeit-firstapp.firebaseapp.com',
    storageBucket: 'abschlussarbeit-firstapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8KJiR1sH6m5LUyt5IuPkZcup4Tqki7Co',
    appId: '1:549297268901:android:913dbee84d06fee300454c',
    messagingSenderId: '549297268901',
    projectId: 'abschlussarbeit-firstapp',
    storageBucket: 'abschlussarbeit-firstapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAykJZGy1eVwaRNw60odFOQsCwFaxGIf1Y',
    appId: '1:549297268901:ios:8668697436c81b3100454c',
    messagingSenderId: '549297268901',
    projectId: 'abschlussarbeit-firstapp',
    storageBucket: 'abschlussarbeit-firstapp.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAykJZGy1eVwaRNw60odFOQsCwFaxGIf1Y',
    appId: '1:549297268901:ios:8668697436c81b3100454c',
    messagingSenderId: '549297268901',
    projectId: 'abschlussarbeit-firstapp',
    storageBucket: 'abschlussarbeit-firstapp.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCiY-CfhN388KIk54Q4W2BqDkNBdBTcM',
    appId: '1:549297268901:web:c70448a164c4639e00454c',
    messagingSenderId: '549297268901',
    projectId: 'abschlussarbeit-firstapp',
    authDomain: 'abschlussarbeit-firstapp.firebaseapp.com',
    storageBucket: 'abschlussarbeit-firstapp.firebasestorage.app',
  );
}
